namespace: rollouts-demo-prod

resources:
- monitor-token.yaml
- rollout-manager.yaml
- ../../../apps/rollout/overlays/bluegreen
- ../../../apps/rollout/overlays/canary
- networkpolicy-cicd.yaml
- rollouts-edit-cicd-rolebinding.yaml
