apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rollouts-demo-dev

resources:
- ../../../apps/deploy/base
images:
- digest: sha256:e32df3d15f759d36c323b3dccb7003d38df1a4274d37217715151f085c24c58f
  name: argoproj/rollouts-demo
